included:
  - EOS
excluded:
  - EOS/Vendor
  - EOS/R.generated.swift
  - EOS/UIComponents/LGButton
  - EOS/UIComponents/AttributedLabelView
  - EOS/UIComponents/Switch
cyclomatic_complexity:
  - 10
  - 30
