# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  keychain_name = "ios-build.keychain"
  keychain_password = ENV["KEY_PASSWORD"]
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "300"
  ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  import_certificate(
    certificate_path: ".travis/nbl-dis.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name,
    keychain_password: keychain_password
  )

  lane :fir do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.gemma.fir"
    update_app_identifier(
      xcodeproj: "EOS.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "EOS/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.gemma.fir" # The App Identifier
    )
    disable_automatic_code_signing(
      path: "EOS.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "EOS.xcodeproj",
      profile: ".travis/AdHoc_gemma.mobileprovision", # optional if you use sigh
      target_filter: "EOS", # matches name or type of a target
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
    )
    increment_build_number
    gym(
      xcargs: "-UseNewBuildSystem=YES",
      output_name: "gemma-fir",
      scheme:"EOS",
      workspace:"EOS.xcworkspace",
      configuration:"Release",
      export_method:"ad-hoc",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.gemma.fir" => "iOS AdHoc gemma"
        }
      }
    )
    firim(firim_api_token:"92fc2819f9894e4890c9fd27d4c1d234")
    slack(message: "Successfully distributed gemma to fir, download_url: 	https://fir.im/xrp8 ", slack_url:"https://hooks.slack.com/services/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")
  end

  lane :publish do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.gemma"
    update_app_identifier(
      xcodeproj: "EOS.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "EOS/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.gemma" # The App Identifier
    )
    disable_automatic_code_signing(
      path: "EOS.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "EOS.xcodeproj",
      profile: ".travis/AppStore_gemma.mobileprovision", # optional if you use sigh
      target_filter: "EOS", # matches name or type of a target
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
    )
    increment_build_number
    gym(
      output_name: "gemma-appstore",
      scheme:"EOS",
      workspace:"EOS.xcworkspace",
      configuration:"Release",
      export_method:"app-store",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.gemma" => "iOS AppStore gemma"
        }
      }
    )
    appstore
    slack(message: "Successfully distributed gemma to appstore", slack_url:"https://hooks.slack.com/services/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")
  end
  
   lane :test do
      xcode_select("/Applications/Xcode.app")
      app_identifier="com.nbltrustdev.gemma"
      update_app_identifier(
        xcodeproj: "EOS.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
        plist_path: "EOS/Info.plist", # Path to info plist file, relative to xcodeproj
        app_identifier: "com.nbltrustdev.gemma" # The App Identifier
      )
      disable_automatic_code_signing(
        path: "EOS.xcodeproj"
      )
      update_project_provisioning(
        xcodeproj: "EOS.xcodeproj",
        profile: ".travis/AppStore_gemma.mobileprovision", # optional if you use sigh
        target_filter: "EOS", # matches name or type of a target
        build_configuration: "Release",
        code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
      )
      increment_build_number
      gym(
        output_name: "gemma-testflight",
        scheme:"EOS",
        workspace:"EOS.xcworkspace",
        configuration:"Release",
        export_method:"app-store",
        export_options: {
          compileBitcode: false,
          provisioningProfiles: {
            "com.nbltrustdev.gemma" => "iOS AppStore gemma"
          }
        }
      )
      upload_to_testflight(skip_waiting_for_build_processing:true)
      slack(message: "Successfully distributed gemma to testflight", slack_url:"https://hooks.slack.com/services/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")
    end

end
