language: objective-c
osx_image: xcode9
sudo: false

env:
  global:
    - PROJECT="UINavigationItem+Margin.xcodeproj"
    - SCHEME="UINavigationItem+Margin"
    - SDK="iphonesimulator11.0"
    - ACTION="test"
  matrix:
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 5S,OS=10.3.1"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 6S,OS=10.3.1"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 5S,OS=11.0"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 6S,OS=11.0"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 7 Plus,OS=11.0"

script:
  - set -o pipefail && xcodebuild clean $ACTION -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
